- name: conditions topic
  hosts: local
  vars_prompt:
  - name: Course
    prompt: enter the course details
    private: false
  - name: Duration
    prompt: enter the duration
    private: false
  tasks:
  - name: condition
    ansible.builtin.debug:
      msg: "we are printing {{ Course }} an {{ Duration }}"
    when: Duration | int >=10