- name: looping concept
  hosts: local
  connection: local
  tasks:
  - name: printing data from loop
    ansible.builtin.debug:
      msg: "we are giving data from loop.names {{ item }}"
    loop:
    - Ramesh
    - Suresh
    - Sai
