- name: we are getting data form vars file
  hosts: node
  become: yes
  vars_files:
  - vars.yaml
  tasks:
  - name: Printing file data
    ansible.builtin.debug:
      msg: "iam doing {{ Course }} and {{ Duration }}. Teaching is done by {{ Trainer }}"